@startuml tictactoe
class usantatecla.tictactoe.ConsoleTicTacToe {

	ConsoleTicTacToe()
	- play()
	+ {static} main(String[])

}

class usantatecla.tictactoe.GraphicsTicTacToe {

	- GraphicsTicTacToe()
	- play()
	+ {static} main(String[])

}

class Game as "usantatecla.models.Game"
class consoleView as "usantatecla.tictactoe.views.console.ConsoleView"
class graphicsView as "usantatecla.tictactoe.views.graphics.GraphicsView"

usantatecla.tictactoe.ConsoleTicTacToe *-down-> Game
usantatecla.tictactoe.GraphicsTicTacToe *-down-> Game
usantatecla.tictactoe.ConsoleTicTacToe *-down-> consoleView
usantatecla.tictactoe.GraphicsTicTacToe *-down-> graphicsView
@enduml

@startuml tictactoe.views
class usantatecla.tictactoe.views.ErrorView {

	+ {static} String[] MESSAGES

	+ ErrorView(Error)

}

enum usantatecla.tictactoe.views.Message {
    + TITTLE
	+ NUMBER_PLAYERS
	+ SEPARATOR
	+ VERTICAL_LINE_LEFT
	+ VERTICAL_LINE_CENTERED
	+ VERTICAL_LINE_RIGHT
	+ ENTER_COORDINATE_TO_PUT
	+ ENTER_COORDINATE_TO_REMOVE
	+ COORDINATE_TO_PUT
	+ COORDINATE_TO_REMOVE
	+ COORDINATE_TO_MOVE
	+ PLAYER_WIN
	+ RESUME
	- String message;

	- Message(String)
	+ String getMessage()
	+ write()
	+ writeln()
	+ String toString()

}

class usantatecla.tictactoe.views.View {

	+ View(Game)
	+ interact()
	# {abstract} start()
	# {abstract} play()
	# {abstract} boolean isNewGame()

}

class Game as "usantatecla.tictactoe.models.Game"
class Console as "usantatecla.utils.Console"
class Error as "usantatecla.tictactoe.models.Error"

usantatecla.tictactoe.views.ErrorView *--> Error
usantatecla.tictactoe.views.View *--> Game
usantatecla.tictactoe.views.Message ..> Console
@enduml

@startuml tictactoe.views.console
class usantatecla.tictactoe.views.console.CoordinateView {

    + Coordinate read(String)

}

usantatecla.tictactoe.views.console.CoordinateView ..> usantatecla.tictactoe.views.console.ErrorView

class Coordinate as "usantatecla.tictactoe.models.Coordinate"
class Error as "usantatecla.tictactoe.models.Error"
class Console as "usantatecla.utils.Console"

usantatecla.tictactoe.views.console.CoordinateView ..> Console
usantatecla.tictactoe.views.console.CoordinateView ..> Error
usantatecla.tictactoe.views.console.CoordinateView ..> Coordinate

class usantatecla.tictactoe.views.console.ErrorView {

	ErrorView(Error)
	writeln()

}

class ErrorView as "usantatecla.tictactoe.views.ErrorView"

ErrorView <|-- usantatecla.tictactoe.views.console.ErrorView
usantatecla.tictactoe.views.console.ErrorView ..> Console
usantatecla.tictactoe.views.console.ErrorView *--> Error

class usantatecla.tictactoe.views.console.GameView {

    GameView(Game)
	write()

}

class Game as "usantatecla.tictactoe.models.Game"
class Message as "usantatecla.tictactoe.views.Message"

usantatecla.tictactoe.views.console.GameView *--> Game
usantatecla.tictactoe.views.console.GameView ..> Coordinate
usantatecla.tictactoe.views.console.GameView ..> Message
usantatecla.tictactoe.views.console.GameView ..> usantatecla.tictactoe.views.console.TokenView

class usantatecla.tictactoe.views.console.SubView {

	SubView(Game)

}

usantatecla.tictactoe.views.console.SubView *--> Game

class usantatecla.tictactoe.views.console.PlayView {

    interact()
    - put()
    - move()

}

usantatecla.tictactoe.views.console.SubView <|-- usantatecla.tictactoe.views.console.PlayView
usantatecla.tictactoe.views.console.PlayView ..> Coordinate
usantatecla.tictactoe.views.console.PlayView ..> Message
usantatecla.tictactoe.views.console.PlayView ..> Error
usantatecla.tictactoe.views.console.PlayView ..> usantatecla.tictactoe.views.console.ErrorView
usantatecla.tictactoe.views.console.PlayView ..> usantatecla.tictactoe.views.console.CoordinateView
usantatecla.tictactoe.views.console.PlayView ..> usantatecla.tictactoe.views.console.GameView
usantatecla.tictactoe.views.console.PlayView ..> usantatecla.tictactoe.views.console.TokenView

class usantatecla.tictactoe.views.console.ResumeView {

	boolean interact()

}

class YesNoDialog as "usantatecla.utils.YesNoDialog"

usantatecla.tictactoe.views.console.SubView <|-- usantatecla.tictactoe.views.console.ResumeView
usantatecla.tictactoe.views.console.ResumeView ..> Message
usantatecla.tictactoe.views.console.ResumeView ..> YesNoDialog

class usantatecla.tictactoe.views.console.StartView {

	interact()

}

class LimitedIntDialog as "usantatecla.utils.LimitedIntDialog"

usantatecla.tictactoe.views.console.SubView <|-- usantatecla.tictactoe.views.console.StartView
usantatecla.tictactoe.views.console.StartView ..> Message
usantatecla.tictactoe.views.console.StartView ..> LimitedIntDialog
usantatecla.tictactoe.views.console.StartView ..> usantatecla.tictactoe.views.console.GameView

class usantatecla.tictactoe.views.console.TokenView {

	+ {static} char[] SYMBOLS

	TokenView(Token)
	write()

}

class Token as "usantatecla.tictactoe.models.Token"

usantatecla.tictactoe.views.console.TokenView *--> Token
usantatecla.tictactoe.views.console.TokenView ..> Console

class usantatecla.tictactoe.views.console.ConsoleView {

	+ View(Game)

}

class View as "usantatecla.tictactoe.views.View"

View <|-- usantatecla.tictactoe.views.console.ConsoleView
usantatecla.tictactoe.views.console.ConsoleView *--> usantatecla.tictactoe.views.console.ResumeView
usantatecla.tictactoe.views.console.ConsoleView *--> usantatecla.tictactoe.views.console.PlayView
usantatecla.tictactoe.views.console.ConsoleView *--> usantatecla.tictactoe.views.console.StartView
@enduml

@startuml tictactoe.views.graphics
package javax.swing{}
package java.awt{}

class usantatecla.tictactoe.views.graphics.ChoosePlayersView {

	- {static} String ACCEPT
	- String playersNumber

	~ ChoosePlayersView(JRootPane)
	~ resetPlayersNumber()
	~ String getPlayersNumber()
	+ actionPerformed(ActionEvent)
	+ keyTyped(KeyEvent)
	+ keyPressed(KeyEvent)
	+ keyReleased(KeyEvent)

}

class ErrorView as "usantatecla.tictactoe.views.ErrorView"
class Coordinate as "usantatecla.tictactoe.models.Coordinate"

usantatecla.tictactoe.views.graphics.ChoosePlayersView ..> usantatecla.tictactoe.views.graphics.Constraints
usantatecla.tictactoe.views.graphics.ChoosePlayersView ..> ErrorView
javax.swing <|-- usantatecla.tictactoe.views.graphics.ChoosePlayersView
javax.swing <--* usantatecla.tictactoe.views.graphics.ChoosePlayersView
java.awt <.. usantatecla.tictactoe.views.graphics.ChoosePlayersView

class usantatecla.tictactoe.views.graphics.Constraints {

	~ Constraints(int, int, int, int)

}

java.awt <|-- usantatecla.tictactoe.views.graphics.Constraints

class usantatecla.tictactoe.views.graphics.CoordinateMoveView extends usantatecla.tictactoe.views.graphics.CoordinateView {

    ~ {static} String ENTER_COORDINATE_TO_REMOVE

    ~ CoordinateMoveView()
    ~ resetCoordinates()
    ~ Coordinate[] getCoordinates()
    + actionPerformed(ActionEvent)

}

class Error as "usantatecla.tictactoe.models.Error"
class ErrorView as "usantatecla.tictactoe.views.ErrorView"

usantatecla.tictactoe.views.graphics.CoordinateMoveView ..> Error
usantatecla.tictactoe.views.graphics.CoordinateMoveView ..> ErrorView
usantatecla.tictactoe.views.graphics.CoordinateMoveView *--> "2" Coordinate

class usantatecla.tictactoe.views.graphics.CoordinatePutView extends usantatecla.tictactoe.views.graphics.CoordinateView {

	~ CoordinatePutView()
	~ resetCoordinate()
	~ Coordinate getCoordinate()
	+ actionPerformed(ActionEvent)
	+ keyTyped(KeyEvent )
	+ keyPressed(KeyEvent)
	+ keyReleased(KeyEvent)

}

class Coordinate as "usantatecla.tictactoe.models.Coordinate"

usantatecla.tictactoe.views.graphics.CoordinatePutView ..> ErrorView
usantatecla.tictactoe.views.graphics.CoordinatePutView *--> Coordinate

class usantatecla.tictactoe.views.graphics.CoordinateView {

	# {static} String ENTER_COORDINATE_TO_PUT
	# {static} String ACCEPT

	~ CoordinateView()
	+ {abstract} actionPerformed(ActionEvent)
	+ keyTyped(KeyEvent)
	+ keyPressed(KeyEvent)
	+ keyReleased(KeyEvent)
}

javax.swing <|-- usantatecla.tictactoe.views.graphics.CoordinateView
java.awt <|.. usantatecla.tictactoe.views.graphics.CoordinateView
java.awt <.. usantatecla.tictactoe.views.graphics.CoordinateView
javax.swing <|-- usantatecla.tictactoe.views.graphics.CoordinateView
java.awt <|.. usantatecla.tictactoe.views.graphics.CoordinateView

class usantatecla.tictactoe.views.graphics.GameView {

    ~ GameView(Game)
    ~ write()
    - printRowBoard(int)
    - String getSquareBoardText(int, int)

}

class Game as "usantatecla.tictactoe.models.Game"
class Token as "usantatecla.tictactoe.models.Token"
class Message as "usantatecla.tictactoe.views.Message"

usantatecla.tictactoe.views.graphics.GameView *--> Game
usantatecla.tictactoe.views.graphics.GameView ..> Coordinate
usantatecla.tictactoe.views.graphics.GameView ..> Token
usantatecla.tictactoe.views.graphics.GameView ..> Message
usantatecla.tictactoe.views.graphics.GameView ..> Token
javax.swing <--* usantatecla.tictactoe.views.graphics.GameView
java.awt <.. usantatecla.tictactoe.views.graphics.GameView

class usantatecla.tictactoe.views.graphics.PlayView {

	~ {static final} String ENTER_COORDINATE_TO_PUT
	~ {static final} String ENTER_COORDINATE_TO_REMOVE

	~ PlayView(Game)
	~ interact()
	- put()
	- move()

}

usantatecla.tictactoe.views.graphics.PlayView ..> Coordinate
usantatecla.tictactoe.views.graphics.PlayView ..> Message
usantatecla.tictactoe.views.graphics.PlayView *--> usantatecla.tictactoe.views.graphics.GameView
usantatecla.tictactoe.views.graphics.PlayView *--> usantatecla.tictactoe.views.graphics.CoordinateMoveView
usantatecla.tictactoe.views.graphics.PlayView *--> usantatecla.tictactoe.views.graphics.CoordinatePutView
usantatecla.tictactoe.views.graphics.PlayView ..> ErrorView
javax.swing <|-- usantatecla.tictactoe.views.graphics.PlayView


class usantatecla.tictactoe.views.graphics.ResumeView {

	- boolean newGame;

	~ ResumeView()
	~ boolean isResumedGame()

}

usantatecla.tictactoe.views.graphics.ResumeView ..> Message

class usantatecla.tictactoe.views.graphics.StartView {

    ~ StartView(Game)
    ~ interact()

}

usantatecla.tictactoe.views.graphics.StartView ..> Message
usantatecla.tictactoe.views.graphics.StartView ..> usantatecla.tictactoe.views.graphics.ChoosePlayersView
usantatecla.tictactoe.views.graphics.StartView ..> usantatecla.tictactoe.views.graphics.GameView
javax.swing <|-- usantatecla.tictactoe.views.graphics.StartView

class View as "usantatecla.tictactoe.views.View"

class usantatecla.tictactoe.views.graphics.GraphicsView extends View {

	+ View(Game)

}

usantatecla.tictactoe.views.graphics.GraphicsView *--> usantatecla.tictactoe.views.graphics.PlayView
usantatecla.tictactoe.views.graphics.GraphicsView *--> usantatecla.tictactoe.views.graphics.StartView
usantatecla.tictactoe.views.graphics.GraphicsView ..> usantatecla.tictactoe.views.graphics.ResumeView
@enduml

@startuml tictactoe.models
class  usantatecla.tictactoe.models.Board{
- Token[][] tokens
~ Board()
~ reset()
~ Token getToken(Coordinate)
~ boolean isCompleted()
~ put(Coordinate, Token)
~ move(Coordinate, Coordinate)
- remove(Coordinate)
~ boolean isOccupied(Coordinate, Token)
~ boolean isEmpty(Coordinate)
~ boolean isTicTacToe(Token)
- List<Coordinate> getCoordinates(Token)
}

class ClosedInterval as "usantatecla.tictactoe.utils.ClosedInterval"
class ConcreteCoordinate as "usantatecla.tictactoe.utils.ConcreteCoordinate"
class Direction as "usantatecla.tictactoe.utils.Direction"

usantatecla.tictactoe.models.Board ..> usantatecla.tictactoe.models.Coordinate
usantatecla.tictactoe.models.Board *-down-> "3x3" usantatecla.tictactoe.models.Token
usantatecla.tictactoe.models.Board ..> Direction

class  usantatecla.tictactoe.models.Coordinate{
- {static} Coordinate NULL_COORDINATE
+ {static} int DIMENSION
- {static} ClosedInterval LIMITS
+ Coordinate()
+ Coordinate(int, int)
+ boolean isNull()
+ Error isValid()
+ Direction getDirection(Coordinate)
- boolean inInverseDiagonal()
+ random()
+ boolean equals(Object)
}
ConcreteCoordinate <|-down- usantatecla.tictactoe.models.Coordinate
usantatecla.tictactoe.models.Coordinate ..> usantatecla.tictactoe.models.Error
usantatecla.tictactoe.models.Coordinate ..> Direction
usantatecla.tictactoe.models.Coordinate ..> ClosedInterval

enum  usantatecla.tictactoe.models.Error{
NOT_EMPTY
NOT_OWNER
SAME_COORDINATES
WRONG_COORDINATES
NULL_ERROR
+ boolean isNull()
}

class  usantatecla.tictactoe.models.Game{
- Board board
- Turn turn
+ Game()
+ setUsers(int)
+ boolean isBoardComplete()
+ boolean isUser()
+ Error put(Coordinate)
+ Error move(Coordinate, Coordinate)
+ next()
+ boolean isTicTacToe()
+ Token getToken(Coordinate)
+ Token getToken()
+ int getMaxPlayers()
+ reset()
}
usantatecla.tictactoe.models.Game *-down-> usantatecla.tictactoe.models.Board
usantatecla.tictactoe.models.Game *-down-> usantatecla.tictactoe.models.Turn
usantatecla.tictactoe.models.Game ..> usantatecla.tictactoe.models.Coordinate
usantatecla.tictactoe.models.Game ..> usantatecla.tictactoe.models.Error

class  usantatecla.tictactoe.models.Player{
- Token token
- Board board
~ Player(Token, Board)
~ Error put(Coordinate)
~ Error move(Coordinate, Coordinate)
~ Token getToken()
}
usantatecla.tictactoe.models.Player *-down-> usantatecla.tictactoe.models.Token
usantatecla.tictactoe.models.Player *-down-> usantatecla.tictactoe.models.Board
usantatecla.tictactoe.models.Player ..> usantatecla.tictactoe.models.Coordinate
usantatecla.tictactoe.models.Player ..> usantatecla.tictactoe.models.Error

enum  usantatecla.tictactoe.models.Token{
X
O
NULL
+ boolean isNull()
~ {static} Token get(int)
}

usantatecla.tictactoe.models.Token ..> ClosedInterval

class  usantatecla.tictactoe.models.Turn{
- {static} int NUM_PLAYERS
- Player[] players
- Board board
- int active
- int users
~ Turn(Board)
~ setUsers(int)
~ next()
~ boolean isUser()
~ Error put(Coordinate)
- Player getPlayer()
~ Error move(Coordinate, Coordinate)
~ Token getToken()
}

usantatecla.tictactoe.models.Turn *-down-> "2" usantatecla.tictactoe.models.Player
usantatecla.tictactoe.models.Turn ..down-> usantatecla.tictactoe.models.Board
usantatecla.tictactoe.models.Turn ..down-> usantatecla.tictactoe.models.Token
usantatecla.tictactoe.models.Turn ..down-> usantatecla.tictactoe.models.Coordinate
usantatecla.tictactoe.models.Turn ..down-> usantatecla.tictactoe.models.Error
@enduml