@startuml tictactoe
class  usantatecla.tictactoe.TicTacToe{
- game: Game
- view: View
~ TicTacToe()
- play(): void
+ main(String[]): void
}
usantatecla.tictactoe.TicTacToe *-down-> tictactoe.models.Game
usantatecla.tictactoe.TicTacToe *-down-> tictactoe.views.View
@enduml

@startuml tictactoe.views
class Console as "utils.Console"{}
class Coordinate as "tictactoe.models.Coordinate" {}
class Game as "tictactoe.models.Game"{}
class LimitedIntDialog as " utils.LimitedIntDialog"{}
class Token as "tictactoe.models.Token"{}
class Error as "tictactoe.models.Error"{}

class  tictactoe.views.CoordinateView{
+ read(String): Coordinate
}
Console <..-down- tictactoe.views.CoordinateView
Coordinate <..-down- tictactoe.views.CoordinateView
tictactoe.views.CoordinateView ..> tictactoe.views.ErrorView

class  tictactoe.views.ErrorView{
- {static} MESSAGES: String[]
~ ErrorView(Error)
~ writeln()
}
Console <..-down- tictactoe.views.ErrorView
tictactoe.views.ErrorView *-down-> Error

class  tictactoe.views.GameView{
~ GameView(Game)
~ write()
}
tictactoe.views.GameView ..> tictactoe.views.Message
tictactoe.views.GameView *-down-> Game
tictactoe.views.GameView ..> Coordinate
tictactoe.views.GameView ..> tictactoe.views.TokenView

enum  tictactoe.views.Message{
+ TITLE
+ NUMBER_PLAYERS
+ SEPARATOR
+ VERTICAL_LINE_LEFT
+ VERTICAL_LINE_CENTERED
+ VERTICAL_LINE_RIGHT
+ ENTER_COORDINATE_TO_PUT
+ ENTER_COORDINATE_TO_REMOVE
+ COORDINATE_TO_PUT
+ COORDINATE_TO_REMOVE
+ COORDINATE_TO_MOVE
+	PLAYER_WIN
+ RESUME
- message: String
- Message(String)
~ write(): void
~ writeln(): void
+ toString(): String
}
tictactoe.views.Message ..> Console

class  tictactoe.views.PlayView{
~ PlayView(Game)
~ interact()
- put()
- move()
}
tictactoe.views.SubView <|-down- tictactoe.views.PlayView
tictactoe.views.PlayView ..> Game
tictactoe.views.PlayView ..> tictactoe.views.TokenView
tictactoe.views.PlayView ..> tictactoe.views.Message
tictactoe.views.PlayView ..> Coordinate
tictactoe.views.PlayView ..> tictactoe.views.CoordinateView
tictactoe.views.PlayView ..> tictactoe.views.ErrorView

class  tictactoe.views.ResumeView{
~ ResumeView(Game)
~ interact(): boolean

}
tictactoe.views.SubView <|-down- tictactoe.views.ResumeView
tictactoe.views.ResumeView ..> Game
tictactoe.views.ResumeView ..> tictactoe.views.Message

class tictactoe.views.StartView{
~ StartView(Game)
~ interact()
}
tictactoe.views.SubView <|-down- tictactoe.views.StartView
tictactoe.views.StartView ..> Game
tictactoe.views.StartView ..> tictactoe.views.GameView
tictactoe.views.StartView ..> LimitedIntDialog
tictactoe.views.StartView ..> tictactoe.views.Message

class tictactoe.views.SubView{
~ SubView(Game)
}

tictactoe.views.SubView *--> Game

class tictactoe.views.TokenView{
- {static} SYMBOLS: char
~ TokenView(Token)
~ write()
}
tictactoe.views.TokenView *--> Token
tictactoe.views.TokenView ..> Console

class  tictactoe.views.View{
+ View(Game)
+ interact()
}
tictactoe.views.View *-down-> Game
tictactoe.views.View *-down-> tictactoe.views.StartView
tictactoe.views.View *-down-> tictactoe.views.PlayView
tictactoe.views.View *-down-> tictactoe.views.ResumeView
@enduml

@startuml tictactoe.models
class Direction as "utils.Direction"{}
class ConcreteCoordinate as "utils.ConcreteCoordinate"{}
class ClosedInterval as "utils.ClosedInterval"{}

class  tictactoe.models.Board{
~ Board()
~ reset()
~ getToken(Coordinate): Token
~ isCompleted(): boolean
~ put(Coordinate, Token)
~ move(Coordinate, Coordinate)
- remove(Coordinate)
~ isOccupied(Coordinate, Token): boolean
~ isEmpty(Coordinate): boolean
~ isTicTacToe(Token): boolean
- getCoordinates(Token): List<Coordinate>
}
tictactoe.models.Board ..> tictactoe.models.Coordinate
tictactoe.models.Board *-down-> "*" tictactoe.models.Token
tictactoe.models.Board ..> Direction

class  tictactoe.models.Coordinate{
- {static} NULL_COORDINATE: Coordinate
+ {static} DIMENSION: int
- {static} LIMITS: ClosedInterval
+ Coordinate()
+ Coordinate(int, int)
+ isNull(): boolean
+ isValid(): Error
+ getDirection(Coordinate): Direction
- inInverseDiagonal(): boolean
+ random()
+ equals(Object): boolean
}
ConcreteCoordinate <|-down- tictactoe.models.Coordinate
tictactoe.models.Coordinate ..> tictactoe.models.Error
tictactoe.models.Coordinate ..> Direction
tictactoe.models.Coordinate ..> ClosedInterval

enum  tictactoe.models.Error{
+ NOT_EMPTY
+ NOT_OWNER
+ SAME_COORDINATES
+ WRONG_COORDINATES
+ NULL_ERROR
+ isNull(): boolean
}

class  tictactoe.models.Game{
+ Game()
+ setUsers(int)
+ isBoardComplete(): boolean
+ isUser(): boolean
+ put(Coordinate): Error
+ move(Coordinate, Coordinate): Error
+ next()
+ isTicTacToe(): boolean
+ getToken(Coordinate): Token
+ getToken(): Token
+ getMaxPlayers(): int
+ reset()
}
tictactoe.models.Game *-down-> tictactoe.models.Board
tictactoe.models.Game *-down-> tictactoe.models.Turn
tictactoe.models.Game ..> tictactoe.models.Coordinate
tictactoe.models.Game ..> tictactoe.models.Error

class  tictactoe.models.Player{
~ Player(Token, Board)
~ put(Coordinate): Error
~ move(Coordinate, Coordinate): Error
~ getToken(): Token
}
tictactoe.models.Player *-down-> tictactoe.models.Token
tictactoe.models.Player *-down-> tictactoe.models.Board
tictactoe.models.Player ..> tictactoe.models.Coordinate
tictactoe.models.Player ..> tictactoe.models.Error

enum  tictactoe.models.Token{
+ X
+ O
+ NULL
+ isNull(): boolean
+ {static} get(int): Token
+ toString(): String
}

tictactoe.models.Token ..> ClosedInterval

class  tictactoe.models.Turn{
- {static} NUM_PLAYERS: int
- active: int
- users: int
~ Turn(Board)
~ setUsers(int)
~ next()
~ isUser(): boolean
~ put(Coordinate): Error
- getPlayer(): Player
~ move(Coordinate, Coordinate): Error
~ getToken(): Token
}

tictactoe.models.Turn *-down-> "*" tictactoe.models.Player
tictactoe.models.Turn *-down-> tictactoe.models.Board
tictactoe.models.Turn ..down-> tictactoe.models.Token
tictactoe.models.Turn ..down-> tictactoe.models.Coordinate
tictactoe.models.Turn ..down-> tictactoe.models.Error

@enduml

@startuml tictactoe.utils
class BufferedReader as "java.io.BufferedReader"{}

class  usantatecla.utils.ClosedInterval{
- min: int
- max: int
+ ClosedInterval(int,int)
+ isIncluded(int): boolean
+ toString(): String
}

class usantatecla.utils.ConcreteCoordinate{
# row: int
# column: int
- {static} ROW: String
- {static} COLUMN: String
# ConcreteCoordinate()
# ConcreteCoordinate(int,int)
+ isNull(): boolean
+ getDirection(Coordinate): Direction
+ inHorizontal(Coordinate): boolean
+ inVertical(Coordinate): boolean
+ inMainDiagonal(): boolean
# read(String)
+ getRow(): int
+ getColumn(): int
+ hashCode(): int
+ equals(Object): boolean
+ toString(): String
}

usantatecla.utils.Coordinate <|..down- usantatecla.utils.ConcreteCoordinate
usantatecla.utils.ConcreteCoordinate ..> usantatecla.utils.Direction
usantatecla.utils.ConcreteCoordinate ..> usantatecla.utils.Console


class usantatecla.utils.Console{
- {static} console: Console
+ {static} instance(): Console
- readString(String): String
+ readString(): String
+ readInt(String): int
~ readChar(String): char
+ writeln()
+ write(String)
+ write(int)
+ writeln(String)
+ writeln(int)
+ write(char)
- writeError(String)
}
usantatecla.utils.Console *-down-> BufferedReader

interface usantatecla.utils.Coordinate{
~ isNull(): boolean
~ getDirection(Coordinate): Direction
~ inHorizontal(Coordinate): boolean
~ inVertical(Coordinate): boolean
~ inMainDiagonal(): boolean
}
usantatecla.utils.Coordinate ..> usantatecla.utils.Direction

enum usantatecla.utils.Direction{
  VERTICAL
  HORIZONTAL
  MAIN_DIAGONAL
  INVERSE_DIAGONAL
  NULL
}

class usantatecla.utils.LimitedIntDialog{
- LIMITS: ClosedInterval
- {static} ERROR_MESSAGE: String
+ LimitedIntDialog(int,int)
+ read(String): int
}

usantatecla.utils.LimitedIntDialog *-down-> usantatecla.utils.ClosedInterval
usantatecla.utils.LimitedIntDialog ..> usantatecla.utils.Console

class usantatecla.utils.NullCoordinate{
- {static} instance: NullCoordinate
+ {static} instance(): Coordinate
+ isNull(): boolean
+ getDirection(Coordinate): Direction
+ inHorizontal(Coordinate): boolean
+ inVertical(Coordinate): boolean
+ inMainDiagonal(): boolean
+ hashCode(): int
+ equals(Object): boolean
+ toString(): String
}
usantatecla.utils.Coordinate <|..down- usantatecla.utils.NullCoordinate
usantatecla.utils.NullCoordinate ..> usantatecla.utils.Direction

class usantatecla.utils.YesNoDialog{
- {static} AFIRMATIVE: char
- {static} NEGATIVE: char
- {static} SUFFIX: String
- {static} MESSAGE: String
- answer: char
+ read(String): boolean
- isAffirmative(): boolean
- getAnswer(): char
- isNegative(): boolean
}
usantatecla.utils.YesNoDialog ..> usantatecla.utils.Console

@enduml
