@startuml paqueteTicTacToe
class View as "tictactoe.views.View" {}
class Game as "tictactoe.models.Game" {}
class StartController as "tictactoe.controllers.StartController" {}
class PlayController as "tictactoe.controllers.PlayController" {}
class ResumeController as "tictactoe.controllers.ResumeController" {}

class  tictactoe.ConsoleTicTacToe{
+ {static} main(String[])
# createView(StartController, PlayController, ResumeController): View
}
tictactoe.TicTacToe <|-down- tictactoe.ConsoleTicTacToe

class  tictactoe.TicTacToe{
- game: Game
- startController: StartController
- playController: PlayController
- resumeController: ResumeController
- view: View
# TicTacToe()
# {abstract} createView(StartController, PlayController, ResumeController): View
# play()
}
tictactoe.TicTacToe --> View
tictactoe.TicTacToe --> Game
tictactoe.TicTacToe --> StartController
tictactoe.TicTacToe --> PlayController
tictactoe.TicTacToe --> ResumeController
@enduml

@startuml paqueteTicTactoeViews
class Error as "tictactoe.types.Error" {}
class Console as "usantatecla.utils.Console" {}

class  tictactoe.views.ErrorView{
+ {static} MESSAGES: String[]
# error: Error
+ ErrorView(Error)
}
tictactoe.views.ErrorView .down.> Error

enum  tictactoe.views.Message{
+ EMPTY
+ NUMBER_PLAYERS
+ SEPARATOR
+ VERTICAL_LINE_LEFT
+ VERTICAL_LINE_CENTERED
+ VERTICAL_LINE_RIGHT
+ ENTER_COORDINATE_TO_PUT
+ ENTER_COORDINATE_TO_REMOVE
+ COORDINATE_TO_PUT
+ COORDINATE_TO_REMOVE
+ COORDINATE_TO_MOVE
+ PLAYER_WIN
+ RESUME
- message: String
- Message(String)
+ getMessage(): String
+ write()
+ writeln()
+ toString(): String
}

tictactoe.views.Message .down.> Console

class tictactoe.views.View {
+ interact()
# {abstract} start()
# {abstract} play()
# {abstract} isResumed(): boolean
}

@enduml

@startuml paqueteTicTactoeViewsConsole
class Error as "tictactoe.models.\nError" {}
class Coordinate as "tictactoe.models.\nCoordinate" {}
class Console as "usantatecla.utils.\nConsole" {}
class Controller as "tictactoe.controllers.\nController" {}
class PlayController as "tictactoe.controllers.\nPlayController" {}
class ResumeController as "tictactoe.controllers.\nResumeController" {}
class YesNoDialog as "usantatecla.utils.\nYesNoDialog" {}
class StartController as "tictactoe.controllers.\nStartController" {}
class LimitedIntDialog as "usantatecla.utils.\nLimitedIntDialog" {}
class Token as "tictactoe.models.\nToken" {}
class Message as "tictactoe.views.\nMessage" {}
class ErrorView as "tictactoe.views.\nErrorView" {}

class tictactoe.views.console.CoordinateView {
+ read(String): Coordinate
}

tictactoe.views.console.CoordinateView .down.> Console
tictactoe.views.console.CoordinateView .down.> Error
tictactoe.views.console.CoordinateView .down.> Coordinate

class  tictactoe.views.console.ErrorView{
~ ErrorView(Error)
~ writeln()
}
tictactoe.views.console.ErrorView .down.> Error
tictactoe.views.console.ErrorView .down.> Console
ErrorView <|-down- tictactoe.views.console.ErrorView

class  tictactoe.views.console.GameView{
~ GameView(Controller)
~ write()
}

tictactoe.views.console.GameView *-down-> Controller
tictactoe.views.console.GameView .down.> Coordinate
tictactoe.views.console.GameView .down.> Message

class  tictactoe.views.console.PlayView{
~ PlayView(PlayController)
~ interact()
- put()
- move()
}

tictactoe.views.console.PlayView *-down-> PlayController
tictactoe.views.console.PlayView .down.> Coordinate
tictactoe.views.console.PlayView .down.> Message
tictactoe.views.console.PlayView .down.> Error

class  tictactoe.views.console.ResumeView{
+ ResumeView(ResumeController)
~ interact(): boolean
}
tictactoe.views.console.ResumeView *-down-> ResumeController
tictactoe.views.console.ResumeView .down.> Message
tictactoe.views.console.ResumeView .down.> YesNoDialog

class tictactoe.views.console.StartView{
~ StartView(StartController)
~ interact(): void
}
tictactoe.views.console.StartView *-down-> StartController
tictactoe.views.console.StartView .down.> Message
tictactoe.views.console.StartView .down.> LimitedIntDialog

class tictactoe.views.console.TokenView{
+ {static} SYMBOLS: char[]
~ TokenView(Token)
~ write()
}
tictactoe.views.console.StartView *-down-> Token
tictactoe.views.console.StartView .down.> Console

class tictactoe.views.console.View{
+ View(StartController, PlayController, ResumeController)
+ interact()
# start()
# play()
# isResumed(): boolean
}
tictactoe.views.console.View *-down-> tictactoe.views.console.StartView
tictactoe.views.console.View *-down-> tictactoe.views.console.PlayView
tictactoe.views.console.View *-down-> tictactoe.views.console.ResumeView


@enduml

@startuml paqueteTicTactoeModels
class ClosedInterval as "usantatecla.utils.\nClosedInterval" {}
class ConcreteCoordinate as "usantatecla.utils.\nConcreteCoordinate" {}
class Direction as "usantatecla.utils.\nDirection" {}
class Error as "tictactoe.types.Error" {}

class  tictactoe.models.Board{
+ Board()
~ reset()
~ getToken(Coordinate): Token
~ boolean isCompleted()
~ put(Coordinate, Token)
~ move(Coordinate, Coordinate)
- remove(Coordinate)
~ isOccupied(Coordinate, Token): boolean
~ isEmpty(Coordinate): boolean
~ isTicTacToe(Token): boolean
- getCoordinates(Token): List<Coordinate>
}

tictactoe.models.Board *-down-> "*" tictactoe.models.Token
tictactoe.models.Board .down.> tictactoe.models.Coordinate
tictactoe.models.Board .down.> Direction

class  tictactoe.models.Coordinate{
- {static} NULL_COORDINATE: Coordinate
+ {static} DIMENSION: int
- {static} LIMITS: ClosedInterval
+ Coordinate()
+ Coordinate(int, int)
+ isNull(): boolean
+ isValid(): Error
+ getDirection(Coordinate): Direction
- inInverseDiagonal(): boolean
+ random()
+ equals(Object): boolean
}
ConcreteCoordinate <|-down- tictactoe.models.Coordinate
tictactoe.models.Coordinate .down.> Error
tictactoe.models.Coordinate .down.> Direction
tictactoe.models.Coordinate .down.> ClosedInterval

class  tictactoe.models.Game{
+ Game()
+ reset()
+ setUsers(int)
+ isBoardComplete(): boolean
+ isUser(): boolean
+ put(Coordinate): Error
+ move(Coordinate, Coordinate): Error
+ next(Error)
+ isTicTacToe(): boolean
+ getToken(Coordinate): Token
+ getToken(): Token
+ getMaxPlayers(): int
}
tictactoe.models.Game *-down-> tictactoe.models.Board
tictactoe.models.Game *-down-> tictactoe.models.Turn
tictactoe.models.Game .down.> tictactoe.models.Coordinate
tictactoe.models.Game .down.> Error

class  tictactoe.models.Player{
~ Player(Token, Board)
~ put(Coordinate): Error
~ move(Coordinate, Coordinate): Error
~ getToken(): Token
}
tictactoe.models.Player *-down-> tictactoe.models.Token
tictactoe.models.Player *-down-> tictactoe.models.Board
tictactoe.models.Player .down.> tictactoe.models.Coordinate
tictactoe.models.Player .down.> Error

enum  tictactoe.models.Token{
+ X
+ O
+ NULL
+ isNull(): boolean
+ {static} get(int): Token
}

tictactoe.models.Token .down.> ClosedInterval

class  tictactoe.models.Turn{
+ {static} NUM_PLAYERS: int
- active: int
- users: int
~ Turn(Board)
~ setUsers(int)
~ next()
~ isUser(): boolean
~ put(Coordinate): Error
~ getPlayer(): Player
~ move(Coordinate, Coordinate): Error
~ getToken(): Token
}

tictactoe.models.Turn *-down-> "*" tictactoe.models.Player
tictactoe.models.Turn *-down-> tictactoe.models.Board
tictactoe.models.Turn .down.-> tictactoe.models.Token
tictactoe.models.Turn .down.-> tictactoe.models.Coordinate
tictactoe.models.Turn .down.-> Error
@enduml

@startuml paqueteTypes

enum  tictactoe.types.Error{
+ NOT_EMPTY
+ NOT_OWNER
+ SAME_COORDINATES
+ NOT_VALID
+ NULL_ERROR
+ isNull(): boolean
}
@enduml

@startuml paqueteTicTactoeControllers
class Game as "tictactoe.models.\nGame" {}
class Coordinate as "tictactoe.models.\nCoordinate" {}
class Error as "tictactoe.types.\nError" {}
class Token as "tictactoe.models.\nToken" {}

class  tictactoe.controllers.Controller{
~ Controller(Game)
+ getToken(Coordinate): Token
}
tictactoe.controllers.Controller *-down-> Game

class  tictactoe.controllers.PlayController{
+ PlayController(Game)
+ isBoardComplete(): boolean
+ isTicTacToe(): boolean
+ getToken(): Token
+ isUser(): boolean
+ put(Coordinate): Error
+ move(Coordinate,Coordinate): Error
}
tictactoe.controllers.Controller <|-down- tictactoe.controllers.PlayController
tictactoe.controllers.PlayController .down.> Coordinate
tictactoe.controllers.PlayController .down.> Error
tictactoe.controllers.PlayController .down.> Game
tictactoe.controllers.PlayController .down.> Token

class  tictactoe.controllers.ResumeController{
+ ResumeController(Game)
+ resume()
}
tictactoe.controllers.Controller <|-down- tictactoe.controllers.ResumeController
tictactoe.controllers.ResumeController .down.> Game

class  tictactoe.controllers.StartController{
+ StartController(Game)
+ setUsers(int)
+ getMaxPlayers(): int
}
tictactoe.controllers.Controller <|-down- tictactoe.controllers.StartController
tictactoe.controllers.StartController .down.> Game
@enduml

@startuml paqueteUtils

class BufferedReader as "java.io.BufferedReader"{}

class  usantatecla.utils.ClosedInterval{
- min: int
- max: int
+ ClosedInterval(int,int)
+ isIncluded(int): boolean
+ toString(): String
}

class usantatecla.utils.ConcreteCoordinate{
# row: int
# column: int
- {static} ROW: String
- {static} COLUMN: String
# ConcreteCoordinate()
# ConcreteCoordinate(int,int)
+ isNull(): boolean
+ getDirection(Coordinate): Direction
+ inHorizontal(Coordinate): boolean
+ inVertical(Coordinate): boolean
+ inMainDiagonal(): boolean
# read(String)
+ getRow(): int
+ getColumn(): int
+ hashCode(): int
+ equals(Object): boolean
+ toString(): String
}

usantatecla.utils.Coordinate <|-down- usantatecla.utils.ConcreteCoordinate
usantatecla.utils.ConcreteCoordinate .down.> usantatecla.utils.Direction
usantatecla.utils.ConcreteCoordinate .down.> usantatecla.utils.Console


class usantatecla.utils.Console{
- {static} console: Console
+ {static} instance(): Console
- readString(String): String
+ readString(): String
+ readInt(String): int
~ readChar(String): char
+ writeln()
+ write(String)
+ write(int)
+ writeln(String)
+ writeln(int)
+ write(char)
- writeError(String)
}
usantatecla.utils.Console *-down-> BufferedReader

interface usantatecla.utils.Coordinate{
~ isNull(): boolean
~ getDirection(Coordinate): Direction
~ inHorizontal(Coordinate): boolean
~ inVertical(Coordinate): boolean
~ inMainDiagonal(): boolean
}
usantatecla.utils.Coordinate .down.> usantatecla.utils.Direction

enum usantatecla.utils.Direction{
  VERTICAL
  HORIZONTAL
  MAIN_DIAGONAL
  INVERSE_DIAGONAL
  NULL
}

class usantatecla.utils.LimitedIntDialog{
- LIMITS: ClosedInterval
- {static} ERROR_MESSAGE: String
+ LimitedIntDialog(int,int)
+ read(String): int
}

usantatecla.utils.LimitedIntDialog *-down-> usantatecla.utils.ClosedInterval
usantatecla.utils.LimitedIntDialog .down.> usantatecla.utils.Console

class usantatecla.utils.NullCoordinate{
- {static} instance: NullCoordinate
+ {static} instance(): Coordinate
+ isNull(): boolean
+ getDirection(Coordinate): Direction
+ inHorizontal(Coordinate): boolean
+ inVertical(Coordinate): boolean
+ inMainDiagonal(): boolean
+ hashCode(): int
+ equals(Object): boolean
+ toString(): String
}
usantatecla.utils.Coordinate <|-down- usantatecla.utils.NullCoordinate
usantatecla.utils.NullCoordinate .down.> usantatecla.utils.Direction

class usantatecla.utils.YesNoDialog{
- {static} AFIRMATIVE: char
- {static} NEGATIVE: char
- {static} SUFFIX: String
- {static} MESSAGE: String
- answer: char
+ read(String): boolean
- isAffirmative(): boolean
- getAnswer(): char
- isNegative(): boolean
}
usantatecla.utils.YesNoDialog .down.> usantatecla.utils.Console
@enduml
